= Subject Proxy Service

== Overview

The `platform.interface.subject_proxy` package shown below defines service interface for the `SUBJECT_PROXY` component in the logical platform architecture.

[.text-center]
.`sm.platform.interface.subject_proxy` package
image::{uml_diagrams_uri}/SM-platform.interface.subject_proxy.svg[id=platform_interface_subject_proxy, align="center"]

This service allows applications to register _data-sets_ used to aggregate data from one or more platform data sources, via their respective services into a coherent set of subject-focused data items required by an application. After registration in the service, data retrievals (e.g. queries or other API calls) are executed by the service, possibly repeated over time, to obtain values sufficiently _current_ for the application's needs. The service provides methods to retrieve single variable values or full data-sets.

== Data-set Package

The `data_set` package shown above defines the representation of _data-sets_ in the Subject proxy service. A data-set is understood as a logical collection of data variables relating to a _subject_, normally a subject of care, but may be any entity. The data-set is defined in terms of _data-set definition_ (`DATA_SET_DEF`) and _data retrieve frames_ (`DATA_RETRIEVE_FRAME`) structures, the latter of which specify how groups of data items are obtained from services in the current system environment. 

Each retrieve frame corresponds to a set of data available from a single source, and having the same a datcurrency, i.e. 'freshness'. Different retrieve frames are used to access different systems and/or to execute distinct queries. A data-set may therefore have associated a number of data retrieve frames in order to populate all of its variables.

When a data-set is installed, the data retrieve frames are executed on a basis determined by the implementation, causing a history of retrieve sample(s) to be created, each of which contains the raw results of an actual retrieval. This enables subsequent calls to the service 'get' methods (`_get_variable_()` and `_get_data_set_()`) to extract variable values from the raw data.

[.tbd]
TBD: details on different return data structures.

== Specifying a Data-set

A data set specification would be provided through a REST API as a text specification, e.g. in JSON or YAML. Such a specification might be derived from an {openehr_decision_language}[openEHR Decision Language Modules^], or some other source. An example is shown below.

[source,yaml]
----
data_set: !!DATA_SET_DEF
    id: antenatal_1.v1.0.3
    subject_id: 137284657
    creating_app_id: task_planning
    variables:
        - name: date_of_birth
          type_name: Date
          source_frame_id: basic_admin
          source_frame_path: /path/to/dob
            
        - name: systolic_bp
          type_name: Quantity
          currency: PT2m
          source_frame_id: bp_obs
          source_frame_path: /data[id2]/events[id7]/data[id4]/items[id5]
            
        - name: diastolic_bp
          type_name: Quantity
          currency: PT2m
          source_frame_id: bp_obs
          source_frame_path: /data[id2]/events[id7]/data[id4]/items[id6]

        - name: is_type1_diabetic
          type_name: Boolean
          source_frame_id: diagnoses
          source_frame_path: /data[id2]/items[id3]
            
    retrieve_frames:
        - id: basic_admin
          retrieve_method: !!API_CALL
              system_id: pas3.nhs.org.uk
              call_name: fhir_admin_request
              parameters:
                  - xxxx: abc
                  - yyyy: def
    
        - id: bp_obs
          retrieve_method: !!QUERY_CALL
              system_id: ehr1.nhs.org.uk
              call_name: aql_execute
              query_text: xxxx
    
        - id: diagnoses
          retrieve_method: !!QUERY_CALL
              system_id: ehr1.nhs.org.uk
              call_name: aql_execute
              query_text: xxxx
----

== Class Definitions

include::{uml_export_dir}/classes/i_subject_proxy_service.adoc[]

include::{uml_export_dir}/classes/data_set_def.adoc[]
include::{uml_export_dir}/classes/variable_def.adoc[]

include::{uml_export_dir}/classes/data_retrieve_frame.adoc[]
include::{uml_export_dir}/classes/data_retrieve_history.adoc[]
include::{uml_export_dir}/classes/data_retrieve_sample.adoc[]

include::{uml_export_dir}/classes/data_set_result.adoc[]
include::{uml_export_dir}/classes/variable_value.adoc[]
include::{uml_export_dir}/classes/variable_value_single.adoc[]
include::{uml_export_dir}/classes/variable_value_list.adoc[]
include::{uml_export_dir}/classes/variable_value_time_series.adoc[]

