= Subject Proxy Service

This service allows real world variables characterising the state of a _subject_, which is usually a patient, but may be some other entity, to be tracked over time, and its conceptual purpose and typical use are described in the {openehr_proc_overview}[openEHR Process and Planning Overview^].

== Service Model

The `platform.interface.subject_proxy` package shown below defines the service interface and related information structures for the `SUBJECT_PROXY` service in the openEHR platform architecture. The subject is registered in the service.

[.text-center]
.`sm.platform.interface.subject_proxy` package
image::{uml_diagrams_uri}/SM-platform.interface.subject_proxy.svg[id=platform_interface_subject_proxy, align="center"]

=== Class Descriptions

include::{uml_export_dir}/classes/i_subject_proxy_service.adoc[leveloffset=+1]

== Data Structures

The data structures used by the Subject Proxy Service are shown below.

[.text-center]
.Subject Proxy structures
image::{uml_diagrams_uri}/SM-platform.interface.subject_proxy-structure.svg[id=platform_interface_subject_proxy_structure, align="center"]

=== Class Definitions

include::{uml_export_dir}/classes/subject_proxy.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/subject_variable.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/subject_data_set.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/data_set_result.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/sample.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/result_set_sample.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/variable_sample.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/variable_value.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/variable_value_single.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/variable_value_list.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/variable_value_time_series.adoc[leveloffset=+1]

== Bindings

The following UML diagram shows the classes and an internal interface relating to bindings.

[.text-center]
.Subject Proxy binding
image::{uml_diagrams_uri}/SM-platform.interface.subject_proxy-binding.svg[id=platform_interface_subject_proxy_binding, align="center"]

A binding (represented by `ENV_BINDING`) is understood as a set of retrieval methods (e.g. API invocations, queries) each associated with a single subject variable (represented by `VARIABLE_BINDING`), for a particular execution environment. A binding may be loaded in the service via the call `_register_binding ()_`.

=== Class Definitions

include::{uml_export_dir}/classes/i_data_binding.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/env_binding.adoc[leveloffset=+1]
include::{uml_export_dir}/classes/variable_binding.adoc[leveloffset=+1]

== Usage

The usage of the service follows the general pattern:

* at system startup, register a binding for an environment, consisting of concrete methods for retrieving and converting data from back-end systems to its variable form;
* during normal operation, register a subject, typically a patient, but may be any other tracked entity, including devices, sites;
* add variable definitions to a subject.

The calling sequence to achieve this is of the logical form:

[source,kotlin]
----
//
// populated in caller
//
sps: I_SUBJECT_PROXY_SERVICE;
var1, var2, var3: SUBJECT_VARIABLE;
env_binding1: ENV_BINDING;

//
// calls to Subject Proxy Service
//
sps.register_binding (env_binding1);

sps.register_subject ("1394850", "individual");
sps.add_subject_variable ("1394850", var1);
sps.add_subject_variable ("1394850", var2);
sps.add_subject_variable ("1394850", var3);
----

The first call registers a _binding_ for a specific environment. See below for how bindings are defined. The next call creates the subject in the service, while the subsequent `_add_subject_variable_` calls are used to build up the proxy variable set for the subject. 

This calling sequence suits system initialisation when specific subject proxy variables are created for global use for specific subjects. Typical variables in a healthcare IT environment include `_date_of_birth_` and `_sex_`.

However many variables are defined by particular applications, including guidelines and planning applications. Accordingly, the service provides a way to register an _application data set_, i.e. a collection of subject variables, for a subject. In this case, the calling sequence will be of the following form.

[source,kotlin]
----
//
// populated in caller
//
sps: I_SUBJECT_PROXY_SERVICE;
ds1: SUBJECT_APP_DATA_SET;
env_binding1: ENV_BINDING;

//
// calls to Subject Proxy Service
//
sps.register_binding (env_binding1);

sps.register_subject ("1394850", "individual");
sps.register_application_data_set (ds1);
sps.register_application_data_set (ds1);
----

In this sequence, the subject variables are established via calls to `_register_application_data_set_`, each of which will cause the addition or modification of subject variables not already defined for the subject. When use of an application or subject ceases, the relevant data sets can be removed easily via the various `_remove_xx_` calls.

The following example illustrates a typical run-time situation for the use of the Subject Proxy Service.

[.text-center]
.Typical Subject Proxy situation
image::{diagrams_uri}/spo_context.svg[id=spo_context, align="center"]

== Specifying a Data-set

A data set specification would be provided through a REST API as a text specification, e.g. in JSON or YAML. Such a specification might be derived from an {openehr_decision_language}[openEHR Decision Language Modules^], or some other source. An example is shown below.

[source,yaml]
----
data_set: !!SUBJECT_DATA_SET
    name: antenatal_1.v1.0.3
    creating_app_id: task_planning
    variables:
        - name: date_of_birth
          type_name: Date
            
        - name: systolic_bp
          type_name: Quantity
          currency: PT2m
            
        - name: diastolic_bp
          type_name: Quantity
          currency: PT2m

        - name: is_type1_diabetic
          type_name: Boolean
----

=== Specifying a Binding

The following shows a partial YAML representation of an `ENV_BINDING`

[source,yaml]
----
binding: !!ENV_BINDING
    variable_bindings:
        - variable_name: date_of_birth
          source_type_name: HL7v3::Date
          primary_method: !!API_CALL
              system_id: pas3.nhs.org.uk
              call_name: cda_admin_request
              parameters:
                  - xxxx: abc
                  - yyyy: def
    
        - variable_name: systolic_bp
          source_type_name: openEHR::DV_QUANTITY
          primary_method: !!QUERY_CALL
              system_id: ehr1.nhs.org.uk
              call_name: aql_execute
              query_text: xxxx
    
        - variable_name: is_type1_diabetic
          source_type_name: FHIR::boolean
          primary_method: !!API_CALL
              system_id: ehr1.nhs.org.uk
              call_name: fhir_execute
              query_text: xxxx
----

