= Preface

== Purpose

This document specifies core components of the openEHR platform a formal, abstract form, for use in developing concrete service API definitions such as SOAP, REST, Google protocol buffers and other interface technologies.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Solution vendors.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].

Related documents include:

* The {openehr_rest_apis}[openEHR REST APIs].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_sm_openehr_platform}.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira}/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].
