= Preface

== Purpose

This document specifies core components of the openEHR platform in a formal, abstract form, for use in developing concrete service API definitions such as SOAP, REST, Google protocol buffers and other interface technologies.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Solution vendors.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].

Related documents include:

* The {openehr_rest_apis}[openEHR REST APIs].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_sm_openehr_platform}[{openehr_sm_openehr_platform}].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list].

Issues may be raised on the {openehr_jira_prs_sm}[specifications Problem Report tracker].

To see changes made due to previously reported issues, see the {openehr_jira_crs_sm}[{component} component Change Request tracker].

