=== DATA_RETRIEVE_SAMPLE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DATA_RETRIEVE_SAMPLE*

h|*Description*
2+a|One retrieval (sample) of a retrieve frame, generated by invocation of the relevant method.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*retrieve_time*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]`
a|Time at which data retrieve attempt made (i.e. when data frame instantiated on caller side, if successful).

h|*0..1*
|*effective_time*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]`
a|Real-world time to which data pertains, if available. Usually obtainable via model-specific call.

h|*1..1*
|*is_unavailable*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Flag to indicate that no data available for this retrieve attempt.

h|*0..1*
|*unavailable_reason*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Potentially a reason for absent data on this retrieve.

h|*0..1*
|*result*: `<<_result_set_class,RESULT_SET>>`
a|Result of retrieve call execution.
|===
