=== DATA_RETRIEVE_FRAME Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DATA_RETRIEVE_FRAME*

h|*Description*
2+a|Package of data items having the same currency and time-window, retrieved by one call or query (`_retrieve_method_`).

Maintains a retrieve history, which consists of one or potentially more 'samples' obtained over time.

In an optimised system, may serve as the source for more than one Data set variable, in which case the `_currency_` will be the lowest currency of all connected variables.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Unique identifier of this retrieve frame in the Subject proxy service.

h|*0..1*
|*currency*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|Required currency of this frame. If not set, only a single retrieve is needed.

h|*1..1*
|*retrieve_method*: `link:/releases/PROC/{proc_release}/task_planning.html#_system_call_class[SYSTEM_CALL^]`
a|System call used to perform retrieval of this data frame.

h|*1..1*
|*retrieve_history*: `<<_data_retrieve_history_class,DATA_RETRIEVE_HISTORY>>`
a|Run-time created retrieval history.

h|*0..1*
|*time_window*: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]>`
a|Time window of this frame as an interval of time-points in past time. If not set, no time-window is used in the retrieve request.

h|*0..1*
|*fallback_method*: `link:/releases/PROC/{proc_release}/task_planning.html#_system_call_class[SYSTEM_CALL^]`
a|Alternative method to use if primary retrieve method fails.
|===
