=== I_ADMIN_SERVICE Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_ADMIN_SERVICE*

h|*Description*
2+a|Primary `ADMIN_SERVICE` Interface.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*list_contributions* ( +
a_service: `<<_platform_service_enumeration,PLATFORM_SERVICE>>[1]`, +
time_interval: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]>[0..1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^]>`
a|Obtain a list of ids of all Contributions in EHR system; an optional time range may be supplied.

.Parameters +
[horizontal]
`_a_service_`:: Name of a versioned content service (enumeration value).

h|*1..1*
|*contribution_count* ( +
a_service: `<<_platform_service_enumeration,PLATFORM_SERVICE>>[1]`, +
time_interval: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]>[0..1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Obtain the count of all Contributions made on EHR system; an optional time range may be supplied.

h|*1..1*
|*versioned_composition_count* ( +
a_service: `<<_platform_service_enumeration,PLATFORM_SERVICE>>[1]`, +
time_interval: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]>[0..1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Obtain the count of all Versioned Compositions on EHR system; an optional time range may be supplied.

h|*1..1*
|*composition_version_count* ( +
a_service: `<<_platform_service_enumeration,PLATFORM_SERVICE>>[1]`, +
time_interval: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]>[0..1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Obtain the count of all Composition Versions on EHR system; an optional time range may be supplied.

h|*0..1*
|*physical_ehr_delete* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
) +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)`
a|Physical deletion of specified EHR.




.Errors
* `ehr_id_does_not_exist`

h|*0..1*
|*physical_party_delete* ( +
a_party_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
)
a|Physical delete of specified Party, along with related Party relationships.




.Errors
* `party_id_does_not_exist`
|===
