=== I_DEFINITION_ADL14 Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_DEFINITION_ADL14*

h|*Description*
2+a|Interface to ADL 1.4 definitions (i.e. archetypes and OPTs) in an EHR 'system'.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_archetype* ( +
an_id: `ARCHETYPE_ID[1]` +
): `Boolean`
a|Return True if an ADL 1.4 archetype with id an_id exists in the service.

h|
|*upload_archetype* ( +
an_arch: `ARCHETYPE[1]` +
) +
*_Post_has_archetype_*: `has_archetype (an_arch.identifier)`
a|Upload a valid ADL 1.4 archetype. If an archetype with the same id already exists, replace it. The archetype must be valid to succeed.




.Errors
* `invalid_archetype`

h|
|*get_archetype* ( +
an_id: `ARCHETYPE_ID[1]` +
): `ARCHETYPE`
a|Get the ADL 1.4 archetype with id an_id.




.Errors
* `artefact_does_not_exist`

h|
|*list_all_archetypes* ( +
row_offset: `Integer[0..1]`, +
rows_to_fetch: `Integer[0..1]` +
): `List<ARCHETYPE_ID>`
a|List all ADL 1.4 archetypes known in the service.

h|
|*list_matching_archetypes* ( +
id_pattern: `String[1]`, +
row_offset: `Integer[0..1]`, +
rows_to_fetch: `Integer[0..1]` +
): `List<ARCHETYPE_ID>`
a|List all archetypes whose identifiers match a regex pattern.




.Errors
* `invalid_id_pattern`

h|
|*delete_archetype* ( +
an_id: `ARCHETYPE_ID[1]` +
) +
*_Pre_artefact_exists_*: `has_artefact (an_id)` +
*_Post_archetype_removed_*: `not has_archetype (an_id)`
a|Delete a previously uploaded archetype.




.Errors
* `invalid_archetype`

h|
|*has_opt* ( +
an_id: `UUID[1]` +
): `Boolean`
a|Return True if ADL 1.4 OPT with id `_an_id_` exists in the service.

h|
|*upload_opt* ( +
arch: `ARCHETYPE[1]` +
)
a|Upload an ADL 1.4 Operational Template (OPT).

.Errors:
* `invalid_template`

h|
|*get_opt* ( +
an_id: `UUID[1]` +
): `ARCHETYPE`
a|Get the ADL 1.4 OPT with id an_id.




.Errors
* `artefact_does_not_exist`

h|
|*list_all_opts* ( +
row_offset: `Integer[0..1]`, +
rows_to_fetch: `Integer[0..1]` +
): `List<UUID>`
a|List all AD 1.4 OPTs known in the service.

h|
|*list_matching_opts* ( +
id_pattern: `String[1]`, +
row_offset: `Integer[0..1]`, +
rows_to_fetch: `Integer[0..1]` +
): `List<ARCHETYPE_ID>`
a|List all OPTs whose identifiers match a regex pattern.




.Errors
* `invalid_id_pattern`

h|
|*delete_opt* ( +
an_id: `UUID[1]` +
) +
*_Pre_has_opt_*: `has_opt (an_id)` +
*_Post_opt_removed_*: `not has_opt (an_id)`
a|Delete a previously uploaded ADL 1.4. OPT.




.Errors
* `invalid_template`
|===
