=== I_DEFINITION_QUERY Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_DEFINITION_QUERY*

h|*Description*
2+a|Interface for storying queries and query sets.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_query* ( +
a_query_name: `String[1]` +
): `Boolean`
a|Return True if the query identified by `_a_query_name_` is registered.

.Parameters +
[horizontal]
`_a_query_name_`:: Qualified name of query.

h|
|*is_valid_query* ( +
a_query_text: `String[1]`, +
a_formalism: `String[1]` +
): `Boolean`
a|Return True if the provided query text is a valid instance of the formalism.

h|
|*register_query* ( +
a_query_text: `String[1]`, +
a_formalism: `String[1]`, +
a_query_name: `String[0..1]` +
): `QUERY_DESCRIPTOR` +
*_Pre_valid_query_*: `is_valid_query(a_query_text)`
a|Register a query under a qualified name. If no name is provided, one is created in the service. Return a Query descriptor containing the query name and unique identifier.

.Parameters +
[horizontal]
`_a_formalism_`:: Case-insensitive name of the formalism of the query text. Values include "AQL" (and "aql").

h|
|*register_query_set* ( +
a_query_set_name: `String[0..1]` +
): `UUID`
a|Register a query set.

TODO: determine details.

h|
|*list_all_queries* ( +
row_offset: `Integer[0..1]`, +
rows_to_fetch: `Integer[0..1]` +
): `List<QUERY_DESCRIPTOR>`
a|List all registered queries.

h|
|*list_matching_queries* ( +
id_pattern: `String[1]`, +
artefact_id_pattern: `String[1]`, +
row_offset: `Integer[0..1]`, +
rows_to_fetch: `Integer[0..1]` +
): `List<QUERY_DESCRIPTOR>`
a|List all registered queries matching an identifier pattern (regex) and an artefact identifier pattern (regex) for artefacts referenced in the query. Either pattern may be the regex for 'match any'.


.Parameters +
[horizontal]
`_id_pattern_`:: PERL regular expression on query identifier.

`_artefact_id_pattern_`:: PERL regular expression on archetype / template identifiers.

.Errors
* `invalid_id_pattern`

h|
|*delete_query* ( +
a_query_name: `String[1]` +
) +
*_Pre_has_query_*: `has_query(a_query_name)` +
*_Post_query_deleted_*: `not has_query (a_query_name)`
a|Delete query with name `_a_query_name_`.


.Parameters +
[horizontal]
`_a_query_name_`:: Qualified query name.

.Errors
* `invalid_query`
|===
