=== I_DEFINITIONS_ADL14 Interface

[cols="^1,2,3"]
|===
h|*Interface*
2+^h|*I_DEFINITIONS_ADL14*

h|*Description*
2+a|Interface to ADL 1.4 definitions (i.e. archetypes and OPTs) in an EHR 'system'.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_archetype* (an_id: `ARCHETYPE_ID`): `Boolean`
a|Return True if an ADL 1.4 archetype with id an_id exists in the service.

h|
|*upload_archetype* (arch: `ARCHETYPE`)
a|Upload an ADL 1.4 archetype. If an archetype with the same id already exists, replace it.

h|
|*get_archetype* (an_id: `ARCHETYPE_ID`): `ARCHETYPE`
a|Get the ADL 1.4 archetype with id an_id.

h|
|*list_archetypes*: `List<ARCHETYPE_ID>`
a|List all ADL 1.4 archetypes known in the service.

h|
|*has_opt* (an_id: `UUID`): `Boolean`
a|Return True if ADL 1.4 OPT with id an_id exists in the service.

h|
|*upload_opt* (arch: `ARCHETYPE`)
a|Upload an ADL 1.4 Operational Template (OPT).

h|
|*get_opt* (an_id: `UUID`): `ARCHETYPE`
a|Get the ADL 1.4 OPT with id an_id.

h|
|*list_opts*: `List<UUID>`
a|List all AD 1.4 OPTs known in the service.
|===
