=== I_DEMOGRAPHIC_SERVICE Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_DEMOGRAPHIC_SERVICE*

h|*Description*
2+a|Primary interface to `DEMOGRAPHIC_SERVICE`.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*create_party* ( +
a_version: `UV_PARTY[1]` +
): `UUID` +
*_Pre_party_definitions_valid_*: `definitions_valid (a_version)` +
*_Pre_content_valid_*: `valid_content (a_version)`
a|Create the first version of a new `PARTY` object. Causes server-side creation of a new `VERSIONED_OBJECT`, `ORIGINAL_VERSION` and new `CONTRIBUTION`.





.Errors
* `definition_unknown`
* `content_invalid`

h|
|*create_party_relationship* ( +
a_version: `UV_PARTY_RELATIONSHIP[1]` +
): `UUID` +
*_Pre_content_valid_*: `valid_content (a_version)`
a|Create the first version of a new `PARTY_RELATIONSHIP`. Causes server-side creation of a new `VERSIONED_OBJECT`, `ORIGINAL_VERSION` and new `CONTRIBUTION`.





.Errors
* `definition_unknown`
* `content_invalid`

h|
|*i_party* ( +
a_versioned_party_id +
): `I_PARTY`
a|Create an `I_PARTY` interface.




.Errors
* `versioned_object_does_not_exist`

h|
|*i_party_relationship* ( +
a_versioned_party_rel_id +
): `I_PARTY_RELATIONSHIP`
a|Create an `I_PARTY_RELATIONSHIP` interface.




.Errors
* `versioned_object_does_not_exist`
|===
