=== I_EHR Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR*

h|*Description*
2+a|Interface for single patient EHR-level operations.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*ehr_status*: `I_EHR_STATUS`
a|Access to `I_EHR_STATUS` interface.

h|*1..1*
|*directory*: `I_EHR_DIRECTORY`
a|Access to `I_EHR_DIRECTORY` interface.

h|*1..1*
|*compositions*: `I_EHR_COMPOSITION`
a|Access to `I_EHR_COMPOSITION` interface.

h|*1..1*
|*contributions*: `I_EHR_CONTRIBUTION`
a|Access to `I_EHR_CONTRIBUTION` interface.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*list_contributions* ( +
auth_tok: `String[1]`, +
ehr_id: `UUID[1]`, +
time_range: `Interval<Iso8601_date_time>[0..1]` +
): `List<UUID>`
a|Obtain a list of identifiers of Contributions in EHR.

.Errors
* `ehr_does_not_exist`

.Parameters +
[horizontal]
`_ehr_id_`:: EHR identifier (UUID).

`_time_range_`:: Optional time range to limit Contributions to.

h|
|*contribution_count* ( +
auth_tok: `String[1]`, +
ehr_id: `UUID[1]`, +
time_range: `Interval<Iso8601_date_time>[0..1]` +
): `Integer`
a|Obtain a count of Contributions in EHR.

.Errors
* `ehr_does_not_exist`

.Parameters +
[horizontal]
`_ehr_id_`:: EHR identifier (Guid).

`_time_range_`:: Optional time range to limit Contributions count to.
|===
