=== I_EHR_DIRECTORY Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR_DIRECTORY*

h|*Description*
2+a|Operations on EHR directory, with implicit Contribution creation.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_directory* ( +
ehr_id: `UUID[1]` +
): `Boolean` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|True if the EHR has a directory structure.

h|
|*has_path* ( +
ehr_id: `UUID[1]`, +
a_path: `String[1]` +
): `Boolean` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|True if path `_a_path_` exists in directory. The `_a_path_` argument consists of slash-separated values of the name attribute of Folders in the directory.




.Errors
* `ehr_id_does_not_exist`

h|
|*create_directory* ( +
ehr_id: `UUID[1]`, +
a_dir_struct: `UV_FOLDER[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)` +
*_Pre_no_directory_*: `not has_directory (ehr_id)`
a|Create a directory in the EHR, based on the provided structure.




.Errors
* `ehr_id_does_not_exist`

h|
|*get_directory* ( +
ehr_id: `UUID[1]` +
): `FOLDER` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get current version of EHR Directory structure, if it exists, else Void.




.Errors
* `ehr_id_does_not_exist`

h|
|*get_directory_at_time* ( +
an_ehr_id: `UUID[1]`, +
a_time: `Iso8601_date_time[0..1]` +
): `FOLDER` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get the version of the Directory extant at time `_a_time_`. If no time supplied, get the latest.


.Parameters +
[horizontal]
`_a_time_`:: Time specifying the extant top version of the Directory.

.Errors
* `ehr_id_does_not_exist`

h|
|*update_directory* ( +
ehr_id: `UUID[1]`, +
a_dir_struct: `UV_FOLDER[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)` +
*_Pre_has_directory_*: `has_directory(ehr_id)`
a|Create or update a directory from a complete structure. Preceding version must be supplied and correct if EHR directory already exists.


.Parameters +
[horizontal]
`_a_dir_struct_`:: Directory structure with which to replace current structure.

.Errors
* `ehr_id_does_not_exist`

h|
|*delete_directory* ( +
ehr_id: `UUID[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)` +
*_Pre_has_directory_*: `has_directory(ehr_id)`
a|Logically delete the directory by creating a new version in which the contents are removed.




.Errors
* `ehr_id_does_not_exist`

h|
|*has_directory_version* ( +
an_ehr_id: `UUID[1]`, +
a_version_uid: `UUID[1]` +
): `Boolean`
a|True if the directory has a version with specified id.




.Errors
* `ehr_id_does_not_exist`

h|
|*get_directory_at_version* ( +
an_ehr_id: `UUID[1]`, +
a_version_uid: `UUID[1]` +
): `FOLDER`
a|Get a particular version of the EHR Directory.




.Errors
* `version_does_not_exist`

h|
|*get_versioned_directory* ( +
an_ehr_id: `UUID[1]` +
): `VERSIONED_FOLDER` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get the `VERSIONED_FOLDER` Directory object for the EHR with `_ehr_id_`.




.Errors
* `ehr_id_does_not_exist`
|===
