=== I_EHR_COMPOSITION Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR_COMPOSITION*

h|*Description*
2+a|Interface for commit and retrieve of Compositions, with implicit Contribution creation.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_composition* ( +
an_ehr_id: `UUID[1]`, +
a_version_uid: `UUID[1]` +
): `Boolean` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Return True if a Composition version with identifier `_a_version_uid_` exists.




.Errors
* `ehr_id_does_not_exist`

h|
|*get_composition* ( +
an_ehr_id: `UUID[1]`, +
a_versioned_object_uid: `UUID[1]` +
): `COMPOSITION` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)` +
*_Pre_has_composition_*: `has_composition (an_ehr_id, a_version_uid)`
a|Retrieve the latest version of a Composition.


.Parameters +
[horizontal]
`_a_versioned_object_uid_`:: Uid of the `VERSIONED_COMPOSITION`.

.Errors
* `ehr_id_does_not_exist`
* `composition_does_not_exist`

h|
|*get_composition_at_time* ( +
an_ehr_id: `UUID[1]`, +
a_versioned_object_uid: `UUID[1]`, +
a_time: `Iso8601_date_time[0..1]` +
): `COMPOSITION` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Retrieve the Composition version extant at a given time, from a Versioned Composition. If no time supplied, get the latest.




.Errors
* `ehr_id_does_not_exist`
* `composition_does_not_exist`

h|
|*create_composition* ( +
an_ehr_id: `UUID[1]`, +
a_comp: `UV_COMPOSITION[1]` +
): `UUID` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)` +
*_Post_has_composition_*: `has_composition (an_ehr_id, Result)` +
*_Pre_composition_definitions_valid_*: `definitions_valid (a_comp)`
a|Create the first version of a new Composition.




.Errors
* `ehr_id_does_not_exist`
* `composition_already_exists`
* `definition_unknown`

h|
|*update_composition* ( +
an_ehr_id: `UUID[1]`, +
a_comp: `UV_COMPOSITION[1]` +
): `UUID` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)` +
*_Pre_composition_definitions_valid_*: `definitions_valid (a_comp)`
a|Update an existing Composition with a new version.




.Errors
* `ehr_id_does_not_exist`
* `composition_does_not_exist`
* `definition_unknown`

h|
|*delete_composition* ( +
an_ehr_id: `UUID[1]`, +
a_version_uid: `UUID[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Logically delete a Composition by creating a new version in which the content is removed and the lifecycle state is set to `523&#124;deleted&#124;`. The `_a_version_uid_` argument identifies the current top Composition Version.




.Errors
* `ehr_id_does_not_exist`
* `composition_does_not_exist`

h|
|*get_composition_at_version* ( +
an_ehr_id: `UUID[1]`, +
a_version_uid: `UUID[1]` +
): `COMPOSITION` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get a particular VERSION of a Composition by version id.


.Parameters +
[horizontal]
`_a_version_uid_`:: Uid of a `VERSION` in a `VERSIONED_COMPOSITION`.

.Errors
* `ehr_does_not_exist`
* `object_version_does_not_exist`

h|
|*get_versioned_composition* ( +
an_ehr_id: `UUID[1]`, +
a_versioned_object_uid: `UUID[1]` +
): `VERSIONED_COMPOSITION` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Retrieve the `VERSIONED_OBJECT` of a Composition by uid.




.Errors
* `ehr_id_does_not_exist`
* `versioned_composition_does_not_exist`
|===
