=== I_EHR_STATUS Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR_STATUS*

h|*Description*
2+a|Interface to `EHR_STATUS` of an EHR, with implicit Contribution creation.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*has_ehr_status_version* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]`, +
a_version_uid: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]` +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)`
a|True if `_an_ehr_status_ver_uid_` is one of the versions of this versioned EHR Status object.




.Errors
* `ehr_id_does_not_exist`

h|*1..1*
|*get_ehr_status* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
): `link:/releases/RM/{rm_release}/ehr.html#_ehr_status_class[EHR_STATUS^]` +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)`
a|Get the current version of the `EHR_STATUS` object for an EHR.




.Errors
* `ehr_id_does_not_exist`

h|*1..1*
|*get_ehr_status_at_time* ( +
a_time: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^][0..1]` +
): `link:/releases/RM/{rm_release}/ehr.html#_ehr_status_class[EHR_STATUS^]` +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)`
a|Get the version of the EHR Status extant at time `_a_time_`. If no time supplied, get the latest.




.Errors
* `ehr_id_does_not_exist`

h|*0..1*
|*set_ehr_queryable* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
) +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)` +
__Post_is_queryable_set__: `get_ehr_status(an_ehr_id).is_queryable`
a|Set the EHR `_is_queryable_` flag to true; this ensures it is included by the query engine.




.Errors
* `ehr_id_does_not_exist`

h|*0..1*
|*set_ehr_modifiable* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
) +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)` +
__Post_is_modifiable_set__: `get_ehr_status(an_ehr_id).is_modifiable`
a|Set the EHR `_is_modifable_` flag to true; this ensures it is treated as active and updatable.




.Errors
* `ehr_id_does_not_exist`

h|*0..1*
|*clear_ehr_queryable* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
) +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)` +
__Post_is_queryable_cleared__: `not get_ehr_status(an_ehr_id).is_queryable`
a|Clear the EHR `_is_queryable_` flag; this ensures it is ignored by the query engine.




.Errors
* `ehr_id_does_not_exist`

h|*0..1*
|*clear_ehr_modifiable* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
) +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)` +
__Post_is_modifiable_cleared__: `not get_ehr_status(an_ehr_id).is_modifiable`
a|Clear the EHR `_is_modifiable_` flag; this ensures it is treated as active.




.Errors
* `ehr_id_does_not_exist`

h|*0..1*
|*update_other_details* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]`, +
a_details: `link:/releases/RM/{rm_release}/data_structures.html#_item_tree_class[ITEM_TREE^][1]` +
) +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)`
a|Update other_details part of `EHR_STATUS` with new content.




.Errors
* `ehr_id_does_not_exist`

h|*1..1*
|*get_ehr_status_at_version* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]`, +
a_version_uid: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
): `link:/releases/RM/{rm_release}/ehr.html#_ehr_status_class[EHR_STATUS^]` +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)`
a|Get a particular version of an EHR Status object.




.Errors
* `ehr_id_does_not_exist`

h|*1..1*
|*get_versioned_ehr_status* ( +
an_ehr_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
): `link:/releases/RM/{rm_release}/ehr.html#_versioned_ehr_status_class[VERSIONED_EHR_STATUS^]` +
 +
__Pre_has_ehr__: `has_ehr (an_ehr_id)` +
__Pre_has_ehr_status_version__: `has_ehr_status_version (an_ehr_id, a_version_uid)`
a|Get the `VERSIONED_EHR_STATUS` object from the EHR with id `_ehr_id_`.




.Errors
* `ehr_id_does_not_exist`
|===
