=== I_EHR_STATUS Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR_STATUS*

h|*Description*
2+a|Interface to `EHR_STATUS` of an EHR, with implicit Contribution creation.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*get_ehr_status* ( +
an_ehr_id: `UUID[1]` +
): `EHR_STATUS` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get the current version of the `EHR_STATUS` object for an EHR.

.Errors
* `ehr_does_not_exist`

h|
|*set_ehr_queryable* ( +
an_ehr_id: `UUID[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Set the EHR `_is_queryable_` flag to true; this ensures it is included by the query engine.

.Errors
* `ehr_does_not_exist`

h|
|*set_ehr_modifiable* ( +
an_ehr_id: `UUID[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Set the EHR `_is_modifable_` flag to true; this ensures it is treated as active and updatable.

.Errors
* `ehr_does_not_exist`

h|
|*clear_ehr_queryable* ( +
an_ehr_id: `UUID[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Clear the EHR `_is_queryable_` flag; this ensures it is ignored by the query engine.

.Errors
* `ehr_does_not_exist`

h|
|*clear_ehr_modifiable* ( +
an_ehr_id: `UUID[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Clear the EHR `_is_modifiable_` flag; this ensures it is treated as active.

.Errors
* `ehr_does_not_exist`

h|
|*update_other_details* ( +
an_ehr_id: `UUID[1]`, +
a_details: `ITEM_TREE[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Update other_details part of `EHR_STATUS` with new content.

.Errors
* `ehr_does_not_exist`

h|
|*get_versioned_ehr_status* ( +
an_ehr_id: `UUID[1]` +
): `VERSIONED_EHR_STATUS` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get the `VERSIONED_EHR_STATUS` object from the EHR with id `_ehr_id_`.

.Errors
* `ehr_does_not_exist`

h|
|*get_ehr_status_at_version* ( +
an_ehr_id: `UUID[1]`, +
a_ehr_status_ver_uid: `UUID[1]` +
): `EHR_STATUS`
a|Get a particular version of an EHR Status object.
|===
