=== I_EHR_DIRECTORY Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR_DIRECTORY*

h|*Description*
2+a|Operations on EHR directory, with implicit Contribution creation.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*create_directory* ( +
ehr_id: `UUID[1]`, +
a_dir_struct: `UV_FOLDER[1]` +
)
a|

h|
|*has_path* ( +
ehr_id: `UUID[1]`, +
a_path: `String[1]` +
): `Boolean` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|True if path `_a_path_` exists in directory. The `_a_path_` argument consists of slash-separated values of the name attribute of Folders in the directory.

.Errors
* `ehr_does_not_exist`

h|
|*update_directory* ( +
ehr_id: `UUID[1]`, +
a_dir_struct: `UV_FOLDER[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Create or update a directory from a complete structure. Preceding version must be supplied and correct if EHR directory already exists.

.Errors
* `ehr_does_not_exist`

.Parameters +
[horizontal]
`_a_dir_struct_`:: Directory structure with which to replace current structure.

h|
|*delete_directory* ( +
ehr_id: `UUID[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Logically delete the directory by creating a new version in which the contents are removed.

.Errors
* `ehr_does_not_exist`

h|
|*get_directory* ( +
ehr_id: `UUID[1]` +
): `FOLDER` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get current version of EHR Directory structure, if it exists, else Void.

.Errors
* ehr_does_not_exist

h|
|*get_directory_at_time* ( +
an_ehr_id: `UUID[1]`, +
a_time: `Iso8601_date_time[1]` +
): `FOLDER` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get the version of the Directory extant at time `_a_time_`.

.Errors
* `ehr_does_not_exist`

.Parameters +
[horizontal]
`_a_time_`:: Time specifying the extant top version of the Directory.

h|
|*get_directory_at_version* ( +
an_ehr_id: `UUID[1]`, +
a_dir_ver_uid: `UUID[1]` +
): `FOLDER`
a|Get a particular version of the EHR Directory.

h|
|*get_versioned_directory* ( +
an_ehr_id: `UUID[1]` +
): `VERSIONED_FOLDER` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Get the `VERSIONED_FOLDER` Directory object for the EHR with ehr_id.

.Errors
* `ehr_does_not_exist`
|===
