=== I_EHR_SERVICE Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR_SERVICE*

h|*Description*
2+a|Primary interface to `EHR_SERVICE` persistent repository.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_ehr* ( +
ehr_id: `UUID[1]` +
): `Boolean`
a|Return True if a EHR with identifier `_ehr_id_` exists.

.Parameters +
[horizontal]
`_ehr_id_`:: EHR identifier.

h|
|*has_ehr_for_subject* ( +
a_subject_id: `PARTY_REF[1]` +
): `Boolean`
a|Returns True if there are EHR(s) for `_a_subject_id_`.


.Parameters +
[horizontal]
`_a_subject_id_`:: Subject identifier.

.Errors
* `ehr_does_not_exist`

h|
|*create_ehr* ( +
an_ehr_status: `EHR_STATUS[0..1]` +
): `UUID` +
*_Post_has_ehr_*: `has_ehr (Result)`
a|Create a new EHR with a system-generated identifier and return the id.

If the `_an_ehr_status_` parameter is provided, it is created as the EHR's `EHR_STATUS`, otherwise a default `EHR_STATUS` is created, in which `_is_modifiable_` and `_is_queryable_` are both True.

h|
|*create_ehr_with_id* ( +
an_ehr_id: `UUID[1]`, +
an_ehr_status: `EHR_STATUS[0..1]` +
): `UUID` +
*_Post_has_ehr_*: `has_ehr (Result)` +
*_Pre_no_duplicate_*: `not has_ehr (an_ehr_id)`
a|Create a new EHR with a provided EHR id; return the id as a safety check.

If the `_an_ehr_status_` parameter is provided, it is created as the EHR's `EHR_STATUS`, otherwise a default `EHR_STATUS` is created, in which `_is_modifiable_` and `_is_queryable_` are both True.


.Parameters +
[horizontal]
`_an_ehr_id_`:: EHR identifier (a UUID).

.Errors
* `ehr_create_fail_duplicate_id`

h|
|*create_ehr_for_subject* ( +
a_subject_id: `PARTY_REF[1]`, +
an_ehr_status: `EHR_STATUS[0..1]` +
): `UUID`
a|Create a new EHR with `EHR_STATUS._subject_` set to point to `_subject_id_`, and return its EHR id.

If the `_an_ehr_status_` parameter is provided, it is created as the EHR's `EHR_STATUS`, otherwise a default `EHR_STATUS` is created, in which `_is_modifiable_` and `_is_queryable_` are both True.


.Parameters +
[horizontal]
`_a_subject_id_`:: Subject identifier.

.Errors
* `ehr_for_subject_already_exists`

h|
|*create_ehr_for_subject_with_id* ( +
an_ehr_id: `UUID[1]`, +
a_subject_id: `PARTY_REF[1]`, +
an_ehr_status: `EHR_STATUS[0..1]` +
): `UUID` +
*_Pre_no_duplicate_*: `not has_ehr (an_ehr_id)`
a|Create a new EHR with EHR id and provided subject id. Return the EHR id as a safety check.

If the `_an_ehr_status_` parameter is provided, it is created as the EHR's `EHR_STATUS`, otherwise a default `EHR_STATUS` is created, in which `_is_modifiable_` and `_is_queryable_` are both True.


.Parameters +
[horizontal]
`_an_ehr_id_`:: EHR identifier (a UUID).

`_a_subject_id_`:: Subject identifier.

.Errors
* `ehr_create_fail_duplicate_id`

h|
|*get_ehr* ( +
an_ehr_id: `UUID[1]` +
): `EHR_SUMMARY` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Retrieve a summarised form of the EHR root object and `EHR_STATUS`.


.Parameters +
[horizontal]
`_an_ehr_id_`:: EHR identifier (a UUID).

.Errors
* `ehr_id_does_not_exist`

h|
|*get_ehrs_for_subject* ( +
a_subject_id: `PARTY_REF[1]` +
): `List<EHR_SUMMARY>`
a|Retrieve EHR or EHRs that have `_ehr_status.subject_id_` = supplied subject id.


.Parameters +
[horizontal]
`_a_subject_id_`:: Subject identifier.

.Errors
* `esubject_id_does_not_exist`

h|
|*i_ehr* ( +
ehr_id: `UUID[1]` +
): `I_EHR`
a|Provide access to an `I_EHR` interface instance for access to the parts of an EHR.




.Errors
* `ehr_id_does_not_exist`
|===
