=== I_EHR_CONTRIBUTION Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR_CONTRIBUTION*

h|*Description*
2+a|Interface for explicit Contribution level operations.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_contribution* ( +
an_ehr_id: `UUID[1]`, +
a_contrib_id: `UUID[1]` +
) +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)`
a|Return True if the Contribution with `_a_contrib_id_` in EHR with id `_an_ehr_id_` exists.

.Errors
* ehr_does_not_exist

h|
|*commit_contribution* ( +
an_ehr_id: `UUID[1]`, +
versions: `List<UPDATE_VERSION>[1]`, +
an_audit: `UPDATE_AUDIT[1]` +
): `UUID` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)` +
*_Post_has_contribution_*: `has_contribution (a_contrib_id)`
a|Commit a Contribution containing any number of `VERSION_UPDATE` objects.

.Errors
* ehr_does_not_exist

h|
|*get_contribution* ( +
an_ehr_id: `UUID[1]`, +
a_contrib_id: `UUID[1]` +
): `CONTRIBUTION` +
*_Pre_has_ehr_*: `has_ehr (an_ehr_id)` +
*_Pre_has_contribution_*: `has_contribution (a_contrib_id)`
a|Return the Contribution with id `_a_contrib_id_` in EHR with id `_an_ehr_id_`.

.Errors
* ehr_does_not_exist
* contribution_does_not_exist

h|
|*list_all_contributions* ( +
row_offset: `Integer[0..1]`, +
rows_to_fetch: `Integer[0..1]` +
): `List<UUID>`
a|List all available Contributions.
|===
