=== I_EHR_INDEX Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_EHR_INDEX*

h|*Description*
2+a|Interface object for the EHR_INDEX service.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*add_ehr_subject* ( +
an_ehr_id: `UUID[1]`, +
a _subject_id: `OBJECT_REF[1]`, +
a_status: `RESOURCE_STATUS[0..1]`, +
a_loc_desc: `LOCATION_DESC[0..1]` +
)
a|Add a subject identifier for the EHR with `_an_ehr_id_`, with an optional resource status and location descriptor.

h|
|*remove_ehr_subject* ( +
an_ehr_id: `UUID[1]`, +
a _subject_id: `OBJECT_REF[1]` +
)
a|Remove the subject identifier association with the EHR with `_an_ehr_id_` (it might remain associated with other EHRs however).

h|
|*update_ehr_subject_status* ( +
an_ehr_id: `UUID[1]`, +
a _subject_id: `OBJECT_REF[1]`, +
a_status: `RESOURCE_STATUS[0..1]` +
)
a|Update subject resource status for the association of the EHR with `_an_ehr_id_` and subject `_a_subject_id_`.

h|
|*update_ehr_subject_loc_desc* ( +
an_ehr_id: `UUID[1]`, +
a _subject_id: `OBJECT_REF[1]`, +
a_loc_desc: `LOCATION_DESC[0..1]` +
)
a|Update location descriptor for the association of the EHR with `_an_ehr_id_` and subject `_a_subject_id_`.
|===
