=== I_PARTY Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_PARTY*

h|*Description*
2+a|Interface for `PARTY` level operations.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*has_party* ( +
a_versioned_party_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Return True if Party exists.

h|*1..1*
|*has_party_version_id* ( +
a_party_version_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if a particular version of a Party exists.

h|*1..1*
|*get_party* ( +
a_versioned_party_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
): `link:/releases/RM/{rm_release}/demographic.html#_party_class[PARTY^]` +
 +
__Pre_has_party__: `has_party (a_versioned_party_id)`
a|Get the current Version of a Party.




.Errors
* `versioned_object_does_not_exist`

h|*1..1*
|*get_party_at_time* ( +
a_versioned_party_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]`, +
a_time: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^][1]` +
): `link:/releases/RM/{rm_release}/demographic.html#_party_class[PARTY^]`
a|Get the Version of a Party current at `_a_time_`.




.Errors
* `versioned_object_does_not_exist`

h|*1..1*
|*update_party* ( +
a_versioned_party_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]`, +
a_version: `<<_uv_party_class,UV_PARTY>>[1]` +
): `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^]` +
 +
__Pre_party_definitions_valid__: `definitions_valid (a_version)` +
__Pre_has_party__: `has_party (a_versioned_party_id)`
a|Update a `PARTY` with a new Version. Causes server-side creation of a new `ORIGINAL_VERSION` and `CONTRIBUTION`.





.Errors
* `versioned_object_does_not_exist`
* `object_version_does_not_exist`
* `definition_unknown`
* `content_invalid`

h|*0..1*
|*delete_party* ( +
a_versioned_party_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
) +
 +
__Pre_has_party__: `has_party (a_versioned_party_id)` +
__Post_party_deleted__: `not has_party (a_versioned_party_id)`
a|Delete an existing Party.




.Errors
* `versioned_object_does_not_exist`

h|*1..1*
|*get_party_at_version* ( +
a_party_version_id: `link:/releases/BASE/{base_release}/base_types.html#_uuid_class[UUID^][1]` +
): `link:/releases/RM/{rm_release}/demographic.html#_party_class[PARTY^]` +
 +
__Pre_has_party_version__: `has_party_version (a_party_version_id)`
a|Get a particular Party Version.




.Errors
* `object_version_does_not_exist`
|===
