=== I_PARTY_RELATIONSHIP Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_PARTY_RELATIONSHIP*

h|*Description*
2+a|Interface for `PARTY_RELATIONSHIP` operations.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_party_relationship* ( +
a_versioned_party_id: `UUID[1]` +
): `Boolean`
a|Return True if Party relationship exists in service.

h|
|*get_party_relationship* ( +
a_versioned_party_id: `UUID[1]` +
): `PARTY_RELATIONSHIP`
a|Get the current Version of a Party relationship.

h|
|*get_party_relationship_at_version* ( +
a_party_version_id: `UUID[1]` +
): `PARTY_RELATIONSHIP`
a|Get a particular Party relationship Version.

h|
|*get_party_relationship_at_time* ( +
a_versioned_party_id: `UUID[1]`, +
a_time: `Iso8601_date_time[1]` +
): `PARTY_RELATIONSHIP`
a|Get the Version of a Party relationship current at `_a_time_`.

h|
|*update_party_relationship* ( +
a_versioned_party_id: `UUID[1]`, +
a_version: `PARTY_RELATIONSHIP[1]` +
): `UUID`
a|Update a Party relationship with a new Version.

h|
|*delete_party_relationship* ( +
a_versioned_party_id: `UUID[1]` +
)
a|Delete an existing Party relationship.
|===
