=== I_PARTY_RELATIONSHIP Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*I_PARTY_RELATIONSHIP*

h|*Description*
2+a|Interface for `PARTY_RELATIONSHIP` operations.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_party_relationship* ( +
a_versioned_party_rel_id: `UUID[1]` +
): `Boolean`
a|Return True if Party relationship exists in service.

h|
|*get_party_relationship* ( +
a_versioned_party_rel_id: `UUID[1]` +
): `PARTY_RELATIONSHIP`
a|Get the current Version of a Party relationship.




.Errors
* `versioned_object_does_not_exist`

h|
|*get_party_relationship_at_time* ( +
a_versioned_party_rel_id: `UUID[1]`, +
a_time: `Iso8601_date_time[1]` +
): `PARTY_RELATIONSHIP`
a|Get the Version of a Party relationship current at `_a_time_`.




.Errors
* `versioned_object_does_not_exist`

h|
|*update_party_relationship* ( +
a_versioned_party_rel_id: `UUID[1]`, +
a_version: `UV_PARTY_RELATIONSHIP[1]` +
): `UUID` +
 +
_Pre_party_definitions_valid_: `definitions_valid (a_version)` +
_Pre_has_relationship_: `has_party_relationship (a_versioned_party_rel_id)`
a|Update a `PARTY_RELATIONSHIP` with a new Version. Causes server-side creation of a new `ORIGINAL_VERSION` and `CONTRIBUTION`.




.Errors
* `versioned_object_does_not_exist`
* `object_version_does_not_exist`
* `definition_unknown`
* `content_invalid`

h|
|*delete_party_relationship* ( +
a_versioned_party_rel_id: `UUID[1]` +
) +
 +
_Pre_has_relationship_: `has_party_relationship (a_versioned_party_rel_id)` +
_Post_relationship_deleted_: `not has_party_relationship (a_versioned_party_rel_id)`
a|Delete an existing Party relationship.




.Errors
* `versioned_object_does_not_exist`

h|
|*get_party_relationship_at_version* ( +
a_party_rel_version_id: `UUID[1]` +
): `PARTY_RELATIONSHIP`
a|Get a particular Party relationship Version.




.Errors
* `object_version_does_not_exist`
|===
