=== QUERY_DESCRIPTOR Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*QUERY_DESCRIPTOR*

h|*Description*
2+a|Object describing a query in terms of its unique identifier, name under which it is currently registered and registration time under the current name.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*qualified_query_name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Unique qualified name of query. Qualified names follow patterns such as `<namespace>::<query_name>`

e.g. "ehr::all_over_50_women".

h|*0..1*
|*version*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Query semver.org version number.

h|*1..1*
|*registration_time*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]`
a|Time query was registered in the service.

h|*1..1*
|*formalism*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Formalism of the query, matching one of:

* "aql";
* any other string value.

h|*0..1*
|*source*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Source query text to be executed (prior to parameter substitution).
|===
