=== SAMPLE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__SAMPLE<T> (abstract)__*

h|*Description*
2+a|One retrieval (sample) of a data 'block', generated by invocation of some retrieval method. The concept of a 'sample' encompasses retrieval (attempt) time-stamp, availability status, and result, if available. Every retrieval attempt will generate a new Sample object, regardless of whether data was actually available or not.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*retrieve_time*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]`
a|Time at which data retrieve attempt made (i.e. when data frame instantiated on caller side, if successful).

h|*0..1*
|*effective_time*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]`
a|Real-world time to which data pertains, if available. Usually obtainable via model-specific call.

h|*1..1*
|*is_unavailable*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Flag to indicate that no data available for this retrieve attempt.

h|*0..1*
|*unavailable_reason*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Potentially a reason for absent data on this retrieve.

h|*0..1*
|*result*: `T`
a|Result of retrieve call execution.
|===
