=== SUBJECT_VARIABLE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*SUBJECT_VARIABLE*

h|*Description*
2+a|A single subject variable whose data may take various forms, including atomic, list and time series.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*source*: `<<_i_data_binding_interface,I_DATA_BINDING>>`
a|Source data binding.

h|*0..1*
|*history*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_variable_sample_class,VARIABLE_SAMPLE>>>`
a|Samples constituting the retrieve history of this variable.

h|*0..1*
|*last_result*: `<<_result_set_sample_class,RESULT_SET_SAMPLE>>`
a|Most recently obtained result.

h|*1..1*
|*name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Canonical name by which this item is known in the service. Typically required to be a legal variable name in a programming language.

h|*1..1*
|*type_name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Formal type name from defining model.

h|*0..1*
|*currency*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|Required currency of this data item. If not set, most recent available is valid.

h|*0..1*
|*ask_user*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|If set true, the service should attempt to obtain the data item from a live user.

TODO: can only work if access method defined.

h|*1..1*
|*is_manual*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if this variable is obtained by manual notification, typically from a worker observing the subject in a point of care situation.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value* (): `<<_variable_sample_class,VARIABLE_SAMPLE>>`
a|Extract the value from the source retrieve frame, reprocessing if necessary to obtain intended type (single, list, time_series).
|===
