=== VARIABLE_DEF Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*VARIABLE_DEF*

h|*Description*
2+a|One item in a data-set, corresponding to a single symbolic variable. May take various forms, including atomic, list and time series.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*source*: `<<_data_retrieve_frame_class,DATA_RETRIEVE_FRAME>>`
a|Source data frame, derived from `_source_frame_id_`. In an optimised system, may be shared with Data set items from other Data sets.

h|*1..1*
|*name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Symbolic name by which this item is known in the data-set. Typically required to be a legal variable name in a programming language.

h|*1..1*
|*type_name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Formal type name from defining model.

h|*0..1*
|*currency*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|Required currency of this data item. If not set, most recent available is valid.

h|*0..1*
|*time_window*: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]>`
a|Time window of this variable to use in the retrieve request.

h|*1..1*
|*source_frame_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Identifier of Data retrieve frame.

h|*0..1*
|*source_frame_path*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Path within source data frame to obtain this item. If not present, the path `'/'` is assumed, i.e. the item is the sole member of a data frame which has no hierarchical structure.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value* (): `<<_variable_value_class,VARIABLE_VALUE>>`
a|Extract the value from the source retrieve frame, reprocessing if necessary to obtain intended type (single, list, time_series).
|===
