=== VARIABLE_BINDING Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*VARIABLE_BINDING*

h|*Description*
2+a|Binding of a named subject variable such as `is_type1_diabetic` to an extraction method for a particular computing environment.

The `_variable_name_` can be used to match subject variables elsewhere in the Subject Proxy stack.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*primary_method*: `link:/releases/PROC/{proc_release}/task_planning.html#_system_call_class[SYSTEM_CALL^]`
a|System call used to perform retrieval of this data frame.

h|*0..1*
|*fallback_method*: `link:/releases/PROC/{proc_release}/task_planning.html#_system_call_class[SYSTEM_CALL^]`
a|Alternative method to use if primary retrieve method fails.

h|*1..1*
|*variable_name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Symbolic name by which this item is known in client applications or services (e.g. CDS, guidelines execution engine).

Typically required to be a legal variable name in a programming language.

h|*1..1*
|*source_type_name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Formal name of the expected type of the result of executing either the primary or fallback method. This might not be the same type as expected by the calling system.

h|*1..1*
|*is_manual*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if this variable is obtained by manual notification, typically from a worker observing the subject in a point of care situation.
|===
