= SIM-B Data types Package

== Overview

The following UML diagram shows the SIM `rm.data_types` package defining `S_XXX` types corresponding to the RM `rm.data_types` package types.

[.text-center]
.`sm.simplified_im_b.rm.data_types` package
image::{uml_diagrams_uri}/SM-simplified_im_b.rm.data_types.svg[id=sm_simplified_im_b_rm_data_types, align="center"]

== Serial Formats

=== S_DV_TEXT

The following shows the SDT serial formats for an `S_DV_TEXT` instance:

==== Path structure + terse value form

[source,json]
----
{
    "a/b/c/d": "anxiety"
}
----

==== Path structure + regular value form

[source,json]
----
{
    "a/b/c/d|value": "anxiety",
    "a/b/c/d/_mapping:0|match": "=",
    "a/b/c/d/_mapping:0/target|terminology": "SNOMED-CT",
    "a/b/c/d/_mapping:0/target|code": "21794005"
}
----

==== Regular structure + regular value form

[.tbd]
TBD: are the inner attributes supposed to have bars or not, i.e. "|value" etc?

[source,json]
----
{
    "a" : {
        "b" : {
            "c": {
                "d" : {
                    "|value": "anxiety",
                    "_mapping:0|match": "=",
                    "_mapping:0/target|terminology": "SNOMED-CT",
                    "_mapping:0/target|code": "21794005"
                }
            }
        }
    }
}
----

==== Regular structure + terse value form

[source,json]
----
{
    "a" : {
        "b" : {
            "c": {
                "d" : "anxiety"
            }
        }
    }
}
----

=== S_DV_CODED_TEXT

The following shows the SDT serial formats for an `S_DV_CODED_TEXT` instance:

==== Path structure + terse value form

[source,json]
----
{
    "a/b/c/d": "snomed_ct::48694002|anxiety|"
}
----

==== Path structure + regular value form

[source,json]
----
{
    "a/b/c/d|terminology": "SNOMED-CT",
    "a/b/c/d|code": "48694002",
    "a/b/c/d|value": "anxiety",
    "a/b/c/d/_mapping:0|match": "=",
    "a/b/c/d/_mapping:0/target|terminology": "ICD-10",
    "a/b/c/d/_mapping:0/target|code": "H234"

}
----

==== Regular structure + regular value form

[.tbd]
TBD: are the inner attributes supposed to have bars or not, i.e. "|terminology" etc?

[source,json]
----
{
    "a" : {
        "b" : {
            "c": {
                "d" : {
                    "|terminology": "SNOMED-CT",
                    "|code": "48694002",
                    "|value": "anxiety",
                    "_mapping" : [
                        {
                        "|match": "=",
                        "target" {
                            "|terminology": "ICD-10",
                            "|code": "21794005"
                        }
                    ]
                }
            }
        }
    }
}
----

==== Ehrscape STRUCTURED variant - Regular structure + regular value form

[.tbd]
TBD: are the inner attributes supposed to have bars or not, i.e. "|terminology" etc?

[source,json]
----
{
    "a" : {
        "b" : [{
            "c": [{
                "d" : [{
                    "|terminology": "SNOMED-CT",
                    "|code": "48694002",
                    "|value": "anxiety",
                    "_mapping" : [
                        {
                        "|match": "=",
                        "target" {
                            "|terminology": "ICD-10",
                            "|code": "21794005"
                        }
                    ]
                }]
            }]
        }]
    }
}

----
==== Regular structure + terse value form

[source,json]
----
{
    "a" : {
        "b" : {
            "c": {
                "d" : "SNOMED-CT::48694002|anxiety|"
            }
        }
    }
}
----


=== S_DV_QUANTITY

The following shows the SDT serial formats for an `S_DV_QUANTITY` instance:

==== Path structure + terse value form


[source,json]
----
{
    "a/b/c/d": "125 mm[Hg]"
}
----

==== Path structure + regular value form

[source,json]
----
{
    "a/b/c/d|magnitude": 125,
    "a/b/c/d|units":    "mm[Hg]",
    "a/b/c/d|normal_status":  "H",
    "a/b/c/d|magnitude_status": "~",
    "a/b/c/d/_normal_range/lower|magnitude": 2.5,
    "a/b/c/d/_normal_range/lower|unit": "mmol/l",
    "a/b/c/d/_normal_range/upper|magnitude": 6.6,
    "a/b/c/d/_normal_range/upper|unit": "mmol/l",
    "a/b/c/d/_other_reference_ranges:0/meaning|code": "VH",
    "a/b/c/d/_other_reference_ranges:0/meaning|terminology": "local-ranges",
    "a/b/c/d/_other_reference_ranges:0/meaning|value": "Very high",
    "a/b/c/d/_other_reference_ranges:0/lower|magnitude": 10.5,
    "a/b/c/d/_other_reference_ranges:0/lower|unit": "mmol/l",
    "a/b/c/d/_other_reference_ranges:0/upper|magnitude": 16.6,
    "a/b/c/d/_other_reference_ranges:0/upper|unit": "mmol/l"
}

----

==== Ehrscape STRUCTURED variant - Regular structure + regular value form

[.tbd]
TBD: are the inner attributes supposed to have bars or not, i.e. "|magnitude" etc?


[source,json]
----
{
    "a" : {
        "b" : [{
            "c": [{
                "d" : [{
                    "|magnitude": 125,
                    "|units":     "mm[Hg]",
                    "|normal_status": "H",
                    "|magnitude_status": "~",
                    "_normal_range" : [{
                       "lower" : [{
                                "|magnitude": 3.5,
                                "|unit": "mmol/l"
                                }],
                        "upper" : [{
                            "|magnitude": 7.5,
                            "|unit": "mmol/l"
                            }]
                    }],            
                    "_other_reference_ranges" : [
                        { //Text-only meaning
                            "meaning": "Child",
                            "lower" : [{
                                "|magnitude": 10.5,
                                "|unit": "mmol/l"
                                }],
                            "upper" : [{
                                "|magnitude": 10.5,
                                "|unit": "mmol/l"
                                }],
                                
                        },
                        { //Coded meaning
                            "meaning":  [{
                                "|value": "African-American",
                                "|terminology" : "SNOMED-CT",
                                "|code" : "23123456"
                            }],
                            "lower" : [{
                                "|magnitude": 0.5,
                                "|unit": "mmol/l"
                                }],
                            "upper" : [{
                                "|magnitude": 8.5,
                                "|unit": "mmol/l"
                                }]                               
                        }]     
                }]
            }]
        }]
    }]
}
----

==== Regular structure + regular value form

[.tbd]
TBD: are the inner attributes supposed to have bars or not, i.e. "|magnitude" etc?


[source,json]
----
{
  "a" : {
    "b" : {
      "c": {
        "d" : {
          "|magnitude": 125,
          "|units": "mm[Hg]",
          "|normal_status": "H",
          "|magnitude_status": "~",
          "_normal_range" : {
            "lower" : {
                "|magnitude": 3.5,
                "|unit": "mmol/l"
            },
            "upper" : {
              "|magnitude": 7.5,
              "|unit": "mmol/l"
            }
          },            
          "_other_reference_ranges" : [
            { //Text-only meaning
              "meaning": "Child",
              "lower" : {
                "|magnitude": 10.5,
                "|unit": "mmol/l"
              },
              "upper" : {
                "|magnitude": 10.5,
                "|unit": "mmol/l"
              }
            },
            { //Coded meaning
              "meaning":  {
                "|value": "African-American",
                "|terminology" : "SNOMED-CT",
                "|code" : "23123456"
              },
              "lower" : {
                "|magnitude": 0.5,
                "|unit": "mmol/l"
                },
              "upper" : {
                "|magnitude": 8.5,
                "|unit": "mmol/l"
                }                               
            }
          ]
        }     
      }
    }
  }
}
----

==== Regular structure + terse value form

[source,json]
----
{
    "a" : {
        "b" : {
            "c": {
                "d" : "125 mm[Hg]"
            }
        }
    }
}
----


=== S_DV_COUNT

The following shows the SDT serial formats for an `S_DV_COUNT` instance:

==== Path structure + terse value form

[source,json]
----
{
    "a/b/c/d": "23",
}
----
==== Path structure + regular value form

[source,json]
----
{
    "a/b/c/d": "23",
}
----

==== Regular structure + regular value form

In theory, as a DV_ORDERED, DV_COUNT should support other attributes like magnitude_status, normal_status, normal_range etc but not tested yet.

[source,json]
----
{
  "a" : {
    "b" : {
      "c": {
        "d" : 23
      }
    }
  }
}
----

==== Ehrscape STRUCTURED variant Regular structure + regular value form

[NOTE]
Better STRUCTURED (regular) format represents every branch as an array, regardless of whether single or multiple occurrence - needs clarification.

In theory, as a DV_ORDERED, DV_COUNT should support other attributes like magnitude_status, normal_status, normal_range etc but not tested yet.

[source,json]
----
{
    "a" : {
        "b" : [{
            "c": [
                "d" : 23
            ],
          }],
      }]
}
----


=== S_DV_ORDINAL

The following shows the SDT serial formats for an `S_DV_ORDINAL` instance:

==== Path structure + terse form

[source,json]
----
{
    "a/b/c/d": "1|at0004|Absent|",
}
----
==== Path structure + regular value form

[source,json]
----
{
    "a/b/c/d|ordinal": 1,
    "a/b/c/d|code": "at0004",
    "a/b/c/d|value": "Absent",
}
----


==== Regular structure + regular value form

[source,json]
----
{
  "a" : {
      "b" : {
          "c": {
              "d" : {
                  "|code": "at0066",
                  "|value": "Absent",
                  "|ordinal": 1 
              } 
          }
      }
  }
}
----

==== Ehrscape variant STRUCTURED Regular structure + regular value form

[NOTE]
Better STRUCTURED (regular) format represents every branch as an array, regardless of whether single or multiple occurrence - needs clarification.

[source,json]
----
{
    "a" : {
        "b" : [{
            "c": [{
                "d" : [{
                       "|code": "at0066",
                       "|value": "Absent",
                       "|ordinal": 1 
                  }]
              }],
          }],
      }
}
----

=== S_DV_IDENTIFIER

The following shows the SDT serial formats for an `S_DV_IDENTIFIER` instance:


==== Path structure + terse form
[NOTE]
Not supported in Better Ehrscape

[source,json]
----
{
    "a/b/c/d": "1|at0004|Absent|",
}
----
==== Path structure + regular value form

[source,json]
----
{
    "a/b/c/d|identifier": 1,
    "a/b/c/d|type": "GMC number",
    "a/b/c/d|assigner": "GMC-UK",
    "a/b/c/d|issuer": "GMC-UK",
}
----

==== Regular structure + regular value form

[source,json]
----
{
    "a" : {
      "b" : {
          "c": {
              "d" : {
                "|identifier": 1,
                "|type": "GMC number",
                "|assigner": "GMC-UK",
                "|issuer": "GMC-UK"
              },
            },
        },
      }
}
----

==== Ehrscape Regular (STRUCTURED) structure + regular value form

[NOTE]
Better STRUCTURED (regular) format represents every branch as an array, regardless of whether single or multiple occurrence - needs clarification.

[source,json]
----
{
    "a" : {
      "b" : [{
          "c": [{
              "d" : [{
                "|identifier": 1,
                "|type": "GMC number",
                "|assigner": "GMC-UK",
                "|issuer": "GMC-UK"
              }],
            }],
        }],
      }
}
----



== Class Definitions

include::{uml_export_dir}/classes/s_data_value.adoc[]
include::{uml_export_dir}/classes/s_dv_identifier.adoc[]

include::{uml_export_dir}/classes/s_dv_text.adoc[]
include::{uml_export_dir}/classes/s_dv_coded_text.adoc[]
include::{uml_export_dir}/classes/s_code_phrase.adoc[]

include::{uml_export_dir}/classes/s_dv_parsable.adoc[]

include::{uml_export_dir}/classes/s_dv_quantity.adoc[]
include::{uml_export_dir}/classes/s_dv_count.adoc[]
include::{uml_export_dir}/classes/s_dv_proportion.adoc[]
include::{uml_export_dir}/classes/s_dv_ordinal.adoc[]

